[package]
name = "shrine"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10.3"
thiserror = "1.0.40"

[lib]
name = "shrine"
path = "src/lib.rs"

[[bin]]
name = "shrine"
path = "src/cli.rs"
