[package]
name = "shrine"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10.3"
bson = "2.6.1"
bytes = { version = "1.4.0", features = ["serde"] }
rmp-serde = "1.1.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"

[lib]
name = "shrine"
path = "src/lib.rs"

[[bin]]
name = "shrine"
path = "src/cli.rs"
